on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: zip
        run: |
          mkdir build
          for vol in Y/*/ ; do
            stem=$(basename "$vol")
            (
              cd "$vol" && zip -9r "../../build/${stem}.epub" *
            )
          done
      - uses: actions/upload-artifact@v4
        with:
          path: build
