on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: 'Y'
      - name: zip
        run: |
          mkdir build
          for vol in Y/*/ ; do
            stem=$(basename "$vol")
            (
              cd "$vol" && zip -r "../../build/${stem}.epub" *
            )
          done
      - uses: actions/upload-artifact@v5
        with:
          path: build
          compression-level: 0
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: build/*
